[package]
name = "tomestone"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.33", features = ["wgpu"] }
egui-wgpu = "0.33"
wgpu = "27"
bytemuck = { version = "1", features = ["derive"] }
physis = { path = "../physis" }

[profile.dev]
overflow-checks = false
