[package]
name = "ff-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
ironworks = { version = "0.4.1", features = ["sqpack", "excel", "ffxiv", "mdl"] }
eframe = { version = "0.33", features = ["wgpu"] }
egui-wgpu = "0.33"
wgpu = "27"
bytemuck = { version = "1", features = ["derive"] }

[profile.dev]
overflow-checks = false
